server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: sales
          uri: http://localhost:8082
          predicates:
            - Path=/sales/**, 
        - id: production
          uri: http://localhost:8083
          predicates:
            - Path=/productions/**, 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path=/dashboards/**, # ReadModel에 대한 Path가 생성안되는 문제!
        - id: master
          uri: http://localhost:8085
          predicates:
            - Path=/companies/**, /users/**, /items/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: sales
          uri: http://sales:8080
          predicates:
            - Path=/sales/**, 
        - id: production
          uri: http://production:8080
          predicates:
            - Path=/productions/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: master
          uri: http://master:8080
          predicates:
            - Path=/companies/**, /users/**, /items/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
